const PRODUCTS = [
  { id: 1, name: 'iPhone 15 Pro Max', category: 'Смартфоны', price: 129990, oldPrice: 139990, icon: '📱', rating: 4.9, reviews: 342, badge: 'Хит', description: 'Флагманский смартфон Apple с чипом A17 Pro, титановым корпусом и продвинутой камерой. Дисплей Super Retina XDR 6.7 дюймов.', specs: { 'Экран': '6.7" OLED', 'Процессор': 'A17 Pro', 'Память': '256 ГБ', 'Камера': '48 МП', 'Аккумулятор': '4422 мАч' } },
  { id: 2, name: 'MacBook Pro 16" M3', category: 'Ноутбуки', price: 279990, icon: '💻', rating: 4.8, reviews: 156, badge: 'Новинка', description: 'Профессиональный ноутбук с чипом M3 Pro, 18 часов автономной работы и потрясающим Liquid Retina XDR дисплеем.', specs: { 'Экран': '16" Liquid Retina XDR', 'Процессор': 'Apple M3 Pro', 'ОЗУ': '18 ГБ', 'SSD': '512 ГБ', 'Вес': '2.14 кг' } },
  { id: 3, name: 'AirPods Pro 2', category: 'Аудио', price: 24990, oldPrice: 29990, icon: '🎧', rating: 4.7, reviews: 892, badge: '-17%', description: 'Беспроводные наушники с активным шумоподавлением, адаптивным звуком и пространственным аудио.', specs: { 'Тип': 'Внутриканальные', 'Шумоподавление': 'Активное', 'Время работы': '6 часов', 'Зарядка': 'USB-C, MagSafe' } },
  { id: 4, name: 'iPad Air M2', category: 'Планшеты', price: 79990, icon: '📲', rating: 4.8, reviews: 234, description: 'Мощный и лёгкий планшет с чипом M2, дисплеем Liquid Retina 11 дюймов и поддержкой Apple Pencil Pro.', specs: { 'Экран': '11" Liquid Retina', 'Процессор': 'Apple M2', 'Память': '128 ГБ', 'Вес': '462 г' } },
  { id: 5, name: 'Apple Watch Series 9', category: 'Часы', price: 42990, icon: '⌚', rating: 4.6, reviews: 567, badge: 'Хит', description: 'Умные часы с новым чипом S9, ярким дисплеем и функцией Double Tap для управления жестами.', specs: { 'Дисплей': 'Always-On Retina', 'Чип': 'S9 SiP', 'Защита': 'IP6X, WR50', 'Батарея': '18 часов' } },
  { id: 6, name: 'Sony WH-1000XM5', category: 'Аудио', price: 34990, oldPrice: 39990, icon: '🎧', rating: 4.8, reviews: 423, description: 'Премиальные беспроводные наушники с лучшим в классе шумоподавлением и кристально чистым звуком.', specs: { 'Тип': 'Полноразмерные', 'Время работы': '30 часов', 'Bluetooth': '5.2', 'Вес': '250 г' } },
  { id: 7, name: 'Samsung Galaxy S24 Ultra', category: 'Смартфоны', price: 119990, icon: '📱', rating: 4.7, reviews: 289, badge: 'Новинка', description: 'Флагман Samsung с AI-функциями, титановой рамкой, S Pen и камерой 200 МП.', specs: { 'Экран': '6.8" Dynamic AMOLED', 'Процессор': 'Snapdragon 8 Gen 3', 'Память': '256 ГБ', 'Камера': '200 МП' } },
  { id: 8, name: 'Dell XPS 15', category: 'Ноутбуки', price: 189990, icon: '💻', rating: 4.6, reviews: 178, description: 'Элегантный ноутбук с 15.6" OLED дисплеем, процессором Intel Core i7 и видеокартой NVIDIA RTX.', specs: { 'Экран': '15.6" OLED 3.5K', 'Процессор': 'Intel Core i7', 'ОЗУ': '16 ГБ', 'SSD': '1 ТБ' } },
  { id: 9, name: 'Nintendo Switch OLED', category: 'Игры', price: 34990, icon: '🎮', rating: 4.9, reviews: 1203, badge: 'Хит', description: 'Игровая консоль с ярким 7-дюймовым OLED экраном, широкой подставкой и 64 ГБ встроенной памяти.', specs: { 'Экран': '7" OLED', 'Память': '64 ГБ', 'Время работы': '4.5-9 часов', 'Вес': '420 г' } },
  { id: 10, name: 'DJI Mini 4 Pro', category: 'Дроны', price: 89990, icon: '🚁', rating: 4.8, reviews: 145, badge: 'Новинка', description: 'Компактный дрон с камерой 4K/60fps, всенаправленным обнаружением препятствий и временем полёта до 34 минут.', specs: { 'Камера': '4K/60fps', 'Вес': '249 г', 'Полёт': '34 минуты', 'Дальность': '20 км' } },
  { id: 11, name: 'GoPro Hero 12 Black', category: 'Камеры', price: 49990, icon: '📷', rating: 4.7, reviews: 312, description: 'Экшн-камера с записью 5.3K, улучшенной стабилизацией HyperSmooth 6.0 и HDR-видео.', specs: { 'Видео': '5.3K/60fps', 'Защита': 'Водонепроницаемость 10м', 'Стабилизация': 'HyperSmooth 6.0', 'Батарея': 'Enduro' } },
  { id: 12, name: 'Bose QuietComfort Ultra', category: 'Аудио', price: 44990, icon: '🎧', rating: 4.8, reviews: 234, description: 'Беспроводные наушники с иммерсивным звуком, премиальным шумоподавлением и комфортом на весь день.', specs: { 'Тип': 'Полноразмерные', 'Шумоподавление': 'CustomTune', 'Время работы': '24 часа', 'Bluetooth': '5.3' } },
];

const CATEGORIES = [...new Set(PRODUCTS.map(p => p.category))];
